name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main  # Or whichever branch you want to trigger deploys from

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-roamlinks-plugin mkdocs-blog-plugin mkdocs-rss-plugin mkdocs-awesome-pages-plugin pymdown-extensions mkdocs-exclude

      - name: Build site
        run: mkdocs build --strict

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          force_orphan: true  # Makes a clean, orphaned gh-pages branch if needed
