name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy every time you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MkDocs and plugins
        run: |
          pip install mkdocs-material
          pip install mkdocs-roamlinks-plugin mkdocs-blog-plugin mkdocs-rss-plugin mkdocs-awesome-pages-plugin pymdown-extensions

      - name: Deploy to GitHub Pages
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdocs gh-deploy --force --clean --strict
